#!/usr/bin/env bash
# Read /etc/passwd line by line
while IFS=: read -r username password userid groupid _ home shell
do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $userid"
done < /etc/passwd
