#!/usr/bin/env bash
#contains everything
PID_FILE="/var/run/myscript.pid"

echo "$$" > "$PID_FILE"

term_handler() {
    echo "I hate the kill command"
    rm -f "$PID_FILE"
    exit 0
}

int_handler() {
    echo "Y U no love me?!"
}

quit_handler() {
    rm -f "$PID_FILE"
    exit 0
}

trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
